# Generated by Django 4.0.5 on 2024-06-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FechaPago', models.DateField(verbose_name='%Y-%m-%d')),
                ('Empleado', models.CharField(max_length=50)),
                ('Valor_Procesos', models.IntegerField()),
                ('Otros_pagos', models.IntegerField()),
                ('Descuentos', models.IntegerField()),
                ('Valor_Total_Pagar', models.IntegerField()),
                ('Observaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
