# Generated by Django 4.0.5 on 2024-06-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0001_initial'),
        ('Usuarios', '0002_alter_usuario_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Perfiles.perfiles'),
        ),
    ]
