# Generated by Django 4.0.5 on 2024-06-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nit_Empresa', models.IntegerField()),
                ('Nombre_Empresa', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Representante', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField()),
                ('Estado', models.CharField(default='Activo', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
