# Generated by Django 4.0.5 on 2024-06-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='Estado',
        ),
        migrations.AddField(
            model_name='clientes',
            name='Activo',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
