# Generated by Django 4.0.5 on 2024-06-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_alter_clientes_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Telefono',
            field=models.CharField(max_length=100),
        ),
    ]
