# Generated by Django 4.0.5 on 2024-06-13 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0004_alter_clientes_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Referencia', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Cantidad_Registrada', models.PositiveIntegerField(default=1)),
                ('Estado', models.CharField(default='Ingresado', max_length=50)),
                ('FechaIngreso', models.DateField(verbose_name='%d-%m-%Y')),
                ('FechaSalida', models.DateField(verbose_name='%d-%m-%Y')),
                ('FechaEntregado', models.DateField(blank=True, null=True)),
                ('Activo', models.IntegerField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clientes.clientes')),
                ('UsuarioResponsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
