# Generated by Django 4.0.5 on 2024-06-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='FechaSalida',
            field=models.DateField(blank=True, null=True, verbose_name='%Y-%m-%d'),
        ),
    ]
