# Generated by Django 4.0.5 on 2024-06-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lotes', '0003_alter_lotes_fechaentregado_alter_lotes_fechasalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='FechaEntregado',
            field=models.DateField(blank=True, null=True, verbose_name='%Y-%m-%d'),
        ),
    ]
