# Generated by Django 4.0.5 on 2024-06-15 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso_Operacion',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad_Procesada', models.IntegerField()),
                ('Estado', models.CharField(default='Pendiente liquidar', max_length=100)),
                ('FechaRegistro', models.DateField(verbose_name='%d-%m-%Y')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.operaciones')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso Operacion',
                'verbose_name_plural': 'Procesos Operaciones',
            },
        ),
    ]
