# Generated by Django 4.0.5 on 2024-06-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso_Operacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso_operacion',
            name='Estado',
            field=models.CharField(default='Pendiente Aprobar', max_length=100),
        ),
    ]
